import { useState } from 'react';
import { Shield, KeyRound, Smartphone, Layers, CheckCircle2, AlertOctagon } from 'lucide-react';

export default function LoginMFA({ onComplete }) {
  const [step, setStep] = useState('login'); // 'login', 'mfa', 'session'
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [mfaCode, setMfaCode] = useState('');
  const [attempts, setAttempts] = useState(0);
  const [error, setError] = useState('');
  const [rateLimited, setRateLimited] = useState(false);
  const [authRole, setAuthRole] = useState(null);

  const prefill = (type) => {
    setError('');
    if (type === 'analyst') {
      setEmail('analyst@nexus.org');
      setPassword('nexus_shield_2026');
      setAuthRole('analyst');
    } else {
      setEmail('admin@nexus.org');
      setPassword('organisation');
      setAuthRole('organisation');
    }
  };

  const handleLogin = (e) => {
    e.preventDefault();
    if (rateLimited) return;

    if ((email === 'analyst@nexus.org' && password === 'nexus_shield_2026') || 
        (email === 'admin@nexus.org' && password === 'organisation')) {
      setError('');
      setStep('mfa');
    } else {
      const nextAttempts = attempts + 1;
      setAttempts(nextAttempts);
      if (nextAttempts >= 5) {
        setRateLimited(true);
        setError('RATE LIMIT TRIGGERED: Maximum attempts (5/5) exceeded. Session locked for 60 seconds.');
        setTimeout(() => {
          setAttempts(0);
          setRateLimited(false);
          setError('');
        }, 60000);
      } else {
        setError(`ACCESS DENIED: Invalid credentials. Attempt ${nextAttempts}/5.`);
      }
    }
  };

  const handleMFA = (e) => {
    e.preventDefault();
    if (mfaCode.length === 6 && /^\d+$/.test(mfaCode)) {
      setError('');
      setStep('session');
      setTimeout(() => {
        onComplete(authRole || 'analyst');
      }, 3500);
    } else {
      setError('VERIFICATION FAILED: 6-digit TOTP code must be numeric.');
    }
  };

  return (
    <div className="login-mfa-screen overlay-screen">
      <div className="login-mfa-container">
        {/* Left Panel: Form */}
        <div className="login-mfa-card main-form">
          <div className="card-header-glowing">
            <Shield size={24} className="accent-glow" />
            <h2>NEXUS CENTRAL GATEWAY</h2>
          </div>
          <p className="subtitle">Secure session initialisation portal</p>

          {step === 'login' && (
            <form onSubmit={handleLogin}>
              <div className="form-group">
                <label>Security Identity (Email)</label>
                <input
                  type="email"
                  placeholder="name@nexus-shield.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  disabled={rateLimited}
                  required
                />
              </div>

              <div className="form-group">
                <label>Passphrase</label>
                <input
                  type="password"
                  placeholder="••••••••••••"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  disabled={rateLimited}
                  required
                />
              </div>

              {error && (
                <div className="security-alert fail">
                  <AlertOctagon size={16} />
                  <span>{error}</span>
                </div>
              )}

              <button type="submit" className="nexus-btn primary full-width" disabled={rateLimited}>
                Authenticate Identity
              </button>

              <div className="quick-access">
                <span>QUICK DEPLOYMENT ACCESS:</span>
                <div className="quick-buttons">
                  <button type="button" onClick={() => prefill('analyst')}>
                    Analyst Core
                  </button>
                  <button type="button" onClick={() => prefill('org')}>
                    Organisation Command
                  </button>
                </div>
              </div>
            </form>
          )}

          {step === 'mfa' && (
            <form onSubmit={handleMFA}>
              <div className="form-group">
                <label>Multi-Factor Authentication (TOTP)</label>
                <p className="mfa-instructions">
                  Enter the 6-digit secure authentication code generated by your mobile device.
                </p>
                <input
                  type="text"
                  placeholder="000 000"
                  maxLength={6}
                  value={mfaCode}
                  onChange={(e) => setMfaCode(e.target.value)}
                  required
                  autoFocus
                />
              </div>

              {error && (
                <div className="security-alert fail">
                  <AlertOctagon size={16} />
                  <span>{error}</span>
                </div>
              )}

              <button type="submit" className="nexus-btn primary full-width">
                Verify Session Token
              </button>
              
              <button type="button" className="nexus-btn ghost full-width m-t-10" onClick={() => setStep('login')}>
                Cancel Verification
              </button>
            </form>
          )}

          {step === 'session' && (
            <div className="session-generation">
              <div className="session-spinner" />
              <h3>ESTABLISHING SECURE PIPELINE</h3>
              <div className="session-console">
                <p className="line green">&gt; Signature verification (RS256 JWT): SUCCESS</p>
                <p className="line green">&gt; Refresh Token issued as HttpOnly, Secure cookie: DONE</p>
                <p className="line green">&gt; Auditing login event in PostgreSQL: SUCCESS</p>
                <p className="line cyan">&gt; Performing Redis Blacklist scan for active tokens... CLEAN</p>
                <p className="line cyan">&gt; Mapping RBAC role permissions: {authRole?.toUpperCase()}</p>
                <p className="line blink green">&gt; REDIRECTING TO APPLICATION HUB...</p>
              </div>
            </div>
          )}
        </div>

        {/* Right Panel: Explanations of Security Controls */}
        <div className="login-mfa-card security-controls">
          <h3>NEXUS DEPLOYED DEFENCES</h3>
          
          <div className="control-item">
            <div className="control-title">
              <KeyRound size={16} className="cyan-text" />
              <span>TLS 1.3 & Argon2id Hashing</span>
            </div>
            <p>
              Telemetry & authentication data streams are fully encrypted using TLS 1.3. User passphrases undergo strict salt-injected Argon2id cryptographic hashing to make offline brute-forcing impractical.
            </p>
          </div>

          <div className="control-item">
            <div className="control-title">
              <Smartphone size={16} className="green-text" />
              <span>TOTP app-based MFA (Anti SIM-swap)</span>
            </div>
            <p>
              NEXUS explicitly disables vulnerable SMS-based MFA. By enforcing TOTP app-based authorization (e.g. Google Authenticator), the system eliminates the SIM-swapping attack vector entirely.
            </p>
          </div>

          <div className="control-item">
            <div className="control-title">
              <Layers size={16} className="purple-text" />
              <span>Secure Session Blacklisting</span>
            </div>
            <p>
              RS256 JWT access tokens are set to a short 15-minute lifetime. Refresh tokens reside in Secure, HttpOnly cookies. On logout, Redis blacklisting revokes the session immediately, preventing replay attacks.
            </p>
          </div>

          <div className="security-seal">
            <CheckCircle2 size={14} className="green-text" />
            <span>NEXUS HSTS Compliance Engine (Active)</span>
          </div>
        </div>
      </div>
    </div>
  );
}
